SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[running_vaccination_count]
  FROM [CovidProject].[dbo].[PercentPopulationVaccinated]
